Add hooks for mounting and unmounting backup devices

diff --git a/tests/hook b/tests/hook
--- a/tests/hook
+++ b/tests/hook
@@ -26,7 +26,7 @@ pre-backup-hook )
     exit 1
   fi
   touch hookdata
-  [ -z "${RUN}" ] || touch ${RUN}-pre.ran
+  what=pre
   ;;
 post-backup-hook )
   if [ ! -e hookdata ]; then
@@ -34,6 +34,33 @@ post-backup-hook )
     exit 1
   fi
   rm -f hookdata
-  [ -z "${RUN}" ] || touch ${RUN}-post.ran
+  what=post
+  ;;
+pre-access-hook )
+  if [ -e devhookdata ]; then
+    echo >&2 "ERROR: devhookdata exists"
+    exit 1
+  fi
+  touch devhookdata
+  what=dev-pre
+  ;;
+post-access-hook )
+  if [ ! -e devhookdata ]; then
+    echo >&2 "ERROR: devhookdata does not exist"
+    exit 1
+  fi
+  rm -f devhookdata
+  what=dev-post
+  ;;
+* )
+  echo >&2 "ERROR: unknown hook $RSBACKUP_HOOK"
+  exit 1
   ;;
 esac
+
+if [ ! -z "${RUN}" ]; then
+  touch ${RUN}-${what}.ran
+  if ${RSBACKUP_ACT}; then
+    touch ${RUN}-${what}.acted
+  fi
+fi
