MakeBackup.cc: create outcome earlier
It's required by the post-backup hook.
Add a test for the correct status.

diff --git a/tests/hook b/tests/hook
--- a/tests/hook
+++ b/tests/hook
@@ -35,6 +35,11 @@ post-backup-hook )
   fi
   rm -f hookdata
   what=post
+  if [ ! -z "${EXPECT_STATUS}" \
+       -a "${RSBACKUP_STATUS}" != "${EXPECT_STATUS}" ]; then
+    echo >&3 "ERROR: expected status '${EXPECT_STATUS}' got '${RSBACKUP_STATUS}'"
+    exit 1
+  fi
   ;;
 pre-access-hook )
   if [ -e devhookdata ]; then
