Reject old logfiles rather than upgrading them

diff --git a/tests/upgrade b/tests/upgrade
--- a/tests/upgrade
+++ b/tests/upgrade
@@ -18,64 +18,29 @@ set -e
 
 setup
 
-echo "| --dry-run should do nothing"
+echo "| old logs should be rejected with --dry-run"
 echo "OK: device=device1" > ${WORKSPACE}/logs/1980-01-01-device1-host1-volume1.log
-echo "OK: device=device2" > ${WORKSPACE}/logs/1980-01-01-device2-host1-volume1.log
-echo "OK: device=device1" > ${WORKSPACE}/logs/1980-01-02-device1-host1-volume1.log
-echo "OK: device=device1" > ${WORKSPACE}/logs/1980-01-02-device1-host1-volume2.log
-echo "OK: device=device2" > ${WORKSPACE}/logs/1980-01-02-device2-host1-volume1.log
-echo "OK: device=device2" > ${WORKSPACE}/logs/1980-01-02-device2-host1-volume2.log
-echo "OK: device=device2" > ${WORKSPACE}/logs/1980-01-02-device2-host1-volume3.log
-echo "OK: device=device1" > ${WORKSPACE}/logs/1980-01-03-device1-host1-volume1.log
-echo "OK: device=device1" > ${WORKSPACE}/logs/1980-01-03-device1-host1-volume2.log
-echo "OK: device=device2" > ${WORKSPACE}/logs/1980-01-03-device2-host1-volume1.log
-echo "OK: device=device2" > ${WORKSPACE}/logs/1980-01-03-device2-host1-volume2.log
-echo "OK: device=device2" > ${WORKSPACE}/logs/1980-01-03-device2-host1-volume3.log
+set +e
 s ${RSBACKUP} --dry-run --text /dev/null
+status=$?
+set -e
+if [ $status != 1 ]; then
+  echo >&2 "FAILED: rsbackup failed to reject old logs"
+  exit 1
+fi
 exists ${WORKSPACE}/logs/1980-01-01-device1-host1-volume1.log
-exists ${WORKSPACE}/logs/1980-01-01-device2-host1-volume1.log
-exists ${WORKSPACE}/logs/1980-01-02-device1-host1-volume1.log
-exists ${WORKSPACE}/logs/1980-01-02-device1-host1-volume2.log
-exists ${WORKSPACE}/logs/1980-01-02-device2-host1-volume1.log
-exists ${WORKSPACE}/logs/1980-01-02-device2-host1-volume2.log
-exists ${WORKSPACE}/logs/1980-01-02-device2-host1-volume3.log
-exists ${WORKSPACE}/logs/1980-01-03-device1-host1-volume1.log
-exists ${WORKSPACE}/logs/1980-01-03-device1-host1-volume2.log
-exists ${WORKSPACE}/logs/1980-01-03-device2-host1-volume1.log
-exists ${WORKSPACE}/logs/1980-01-03-device2-host1-volume2.log
-exists ${WORKSPACE}/logs/1980-01-03-device2-host1-volume3.log
 absent ${WORKSPACE}/logs/backups.db
 
-echo "| test simple upgrade"
+echo "| old logs should be rejected"
+set +e
 s ${RSBACKUP} --text /dev/null
-absent ${WORKSPACE}/logs/1980-01-01-device1-host1-volume1.log
-absent ${WORKSPACE}/logs/1980-01-01-device2-host1-volume1.log
-absent ${WORKSPACE}/logs/1980-01-02-device1-host1-volume1.log
-absent ${WORKSPACE}/logs/1980-01-02-device1-host1-volume2.log
-absent ${WORKSPACE}/logs/1980-01-02-device2-host1-volume1.log
-absent ${WORKSPACE}/logs/1980-01-02-device2-host1-volume2.log
-absent ${WORKSPACE}/logs/1980-01-02-device2-host1-volume3.log
-absent ${WORKSPACE}/logs/1980-01-03-device1-host1-volume1.log
-absent ${WORKSPACE}/logs/1980-01-03-device1-host1-volume2.log
-absent ${WORKSPACE}/logs/1980-01-03-device2-host1-volume1.log
-absent ${WORKSPACE}/logs/1980-01-03-device2-host1-volume2.log
-absent ${WORKSPACE}/logs/1980-01-03-device2-host1-volume3.log
-sqlite3 ${WORKSPACE}/logs/backups.db "SELECT host,volume,device,id,rc,status,log FROM backup" > ${WORKSPACE}/got/simple-db.txt
-compare ${srcdir:-.}/expect/upgrade/simple-db.txt ${WORKSPACE}/got/simple-db.txt
-
-echo "| test interrupted upgrade"
-echo "rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(549) [sender=3.0.9]" > ${WORKSPACE}/logs/1980-01-04-device1-host1-volume1.log
-echo "ERROR: device=device1 error=0x1400" >> ${WORKSPACE}/logs/1980-01-04-device1-host1-volume1.log
-s ${RSBACKUP} --text /dev/null
-absent ${WORKSPACE}/logs/1980-01-04-device1-host1-volume1.log
-sqlite3 ${WORKSPACE}/logs/backups.db "SELECT host,volume,device,id,rc,status,log FROM backup" > ${WORKSPACE}/got/interrupted-db.txt
-compare ${srcdir:-.}/expect/upgrade/interrupted-db.txt ${WORKSPACE}/got/interrupted-db.txt
-
-echo "| test badly interrupted upgrade"
-echo "OK: device=device1" > ${WORKSPACE}/logs/1980-01-01-device1-host1-volume1.log
-s ${RSBACKUP} --text /dev/null
-absent ${WORKSPACE}/logs/1980-01-01-device1-host1-volume1.log
-sqlite3 ${WORKSPACE}/logs/backups.db "SELECT host,volume,device,id,rc,status,log FROM backup" > ${WORKSPACE}/got/badly-interrupted-db.txt
-compare ${srcdir:-.}/expect/upgrade/interrupted-db.txt ${WORKSPACE}/got/badly-interrupted-db.txt
+status=$?
+set -e
+if [ $status != 1 ]; then
+  echo >&2 "FAILED: rsbackup failed to reject old logs"
+  exit 1
+fi
+exists ${WORKSPACE}/logs/1980-01-01-device1-host1-volume1.log
+absent ${WORKSPACE}/logs/backups.db
 
 cleanup
